apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    project: roboshop
    teir: db
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017 
  clusterIP: None
  selector:
    app: mongodb
    project: roboshop
    teir: db