apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
    project: roboshop
    teir: db
spec:
  selector:
    matchLabels:
      app: mongodb # has to match .spec.template.metadata.labels
      project: roboshop
      teir: db
  serviceName: "mongodb"
  replicas: {{ .values.statefullset.replicas }}
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        teir: db
    spec:
      containers:
      - name: mongodb
        image: "awsmouli/mongodb:{{ .values.statefullset.imageVersion }}"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi