apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
     app: user
     project: roboshop
     teir: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080