apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    project: roboshop
    teir: db
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
    teir: db