apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    project: roboshop
    teir: db
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379 
  clusterIP: None
  selector:
    app: redis
    project: roboshop
    teir: db