apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    teir: db
spec:
  selector:
    matchLabels:
      app: redis # has to match .spec.template.metadata.labels
      project: roboshop
      teir: db
  serviceName: "redis"
  replicas: {{ .Values.statefullset.replicas }}
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        teir: db
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi