apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
     app: shipping
     project: roboshop
     teir: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080