apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::693226652489:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-IIpFSlJTYsrZ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::693226652489:user/ramesh
      username: ramesh

    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::693226652489:user/moulika
      username: moulika

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 5a715498-783c-40c2-87c3-ba390bf08a8a

