apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    project: roboshop
    teir: db
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672 
  clusterIP: None
  selector:
    app: rabbitmq
    project: roboshop
    teir: db