apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop
    teir: db
spec:
  selector:
    matchLabels:
      app: rabbitmq # has to match .spec.template.metadata.labels
      project: roboshop
      teir: db
  serviceName: "rabbitmq"
  replicas: {{ .Values.statefullset.replicas }}
  template:
    metadata:
      labels:
        app: rabbitmq
        project: roboshop
        teir: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        envFrom:
        - secretRef:
          name: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi